1. Examples of 2D Tensors
2. Tensor Creation in 2D
3. Indexing and Slicing in 2D
4. Basic operations

In [1]:
import torch

In [11]:
a= [ [1,2,3], [4,5,6],[7,8,9]]

In [12]:
A = torch.tensor(a)

In [13]:
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
A.ndimension()

2

In [15]:
A.shape

torch.Size([3, 3])

In [16]:
A.size()

torch.Size([3, 3])

In [17]:
A.numel()

9

In [18]:
A[0][1]

tensor(2)

In [23]:
A[0,0:2] # row 0, col 0-1

tensor([1, 2])

In [25]:
A[1:3,2] # row: 1,2 and col 2

tensor([6, 9])

In [28]:
# dot product torch.mm(A,B)
A = torch.tensor([[0,1,1],[1,0,1]])
B = torch.tensor([ [1,1], [1,1], [-1,1]])
torch.mm(A,B)

tensor([[0, 2],
        [0, 2]])