In [1]:
import torch

In [2]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [4]:
def forward(x):
    y = w*x + b
    return y

In [5]:
x = torch.tensor( [1.0] )
yhat = forward(x)

In [6]:
yhat

tensor([1.], grad_fn=<AddBackward0>)

In [8]:
x = torch.tensor( [[1], [2]])
yhat = forward(x)
yhat

tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [9]:
from torch.nn import Linear

In [17]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)

In [18]:
print ( list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [19]:
x = torch.tensor([0.0])

In [20]:
yhat = model(x)

In [21]:
yhat

tensor([-0.4414], grad_fn=<AddBackward0>)

In [22]:
x = torch.tensor( [ [1.0], [2.0]])

In [23]:
yhat = model(x)
yhat

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)